language: python
python:
    - "2.7"
install:
    - sudo pip install --upgrade -r requirements.txt
    - sudo pip install --upgrade six
before_script:
    - cd test
    - "echo -en \"config = {\n\t'portalcik': '\" > testconfig.py"
    - curl -s -S "http://cik.herokuapp.com" >> testconfig.py
    - echo -e "'\n}" >> testconfig.py
    - cat testconfig.py
    - "export PYTHONPATH=../exoline/:$PYTHONPATH"
    - echo $PYTHONPATH 
script: nosetests --verbose 
notifications:
  email:
    - miketilstra@exosite.com

