# Site settings
title: Exoline
email: danweaver@exosite.com
description: > # this means to ignore newlines until "baseurl:"
  This is the project page for Exoline, a command line interface to 
  the Exosite Internet of Things Platform.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://exosite.github.io/exoline"
twitter_username: exosite
github_username:  dweaver

# Build settings
markdown: kramdown
