# Site settings
title: Exoline
email: danweaver@exosite.com
description:
  Exoline is a command line interface for
  the Exosite Internet of Things platform.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://exosite.github.io/exoline"
twitter_username: exosite
github_username: exosite 

# Build settings
markdown: kramdown
